project:
  type: website
  output-dir: _site

website:
  title: "Baseball Elo Tracker"
  navbar:
    left:
      - text: "Home"
        file: elo_report.qmd

format:
  html:
    theme: default
    toc: true
